# Generated by Django 4.1.2 on 2022-10-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
