# Generated by Django 4.1.2 on 2022-10-22 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(related_name='favorite_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serial',
            name='user',
            field=models.ManyToManyField(related_name='favorite_series', to=settings.AUTH_USER_MODEL),
        ),
    ]
