# Generated by Django 4.1.2 on 2022-10-28 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_movie_user_serial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serial',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='favorite_series', to=settings.AUTH_USER_MODEL),
        ),
    ]
