# Generated by Django 4.1.2 on 2022-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_user_alter_serial_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='serial',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
